### PR TITLE
Fix RessourceManager constructor

### PR DESCRIPTION
**Pull request by christophfroehlich**
I'm currently working on a CI job with downstream builds for ros2_control, and this package here fails.

The API of the RessourceManager has changed. To be able to compile this repository on jazzy+rolling, one has to pass some more arguments to it. I think it is time to branch-off humble and fix that for the newer distros.

### CODE REVIEW

**Review by JafarAbdi — APPROVED** [review]

**Comment by christophfroehlich** [comment]
Well, that is also a possibility. but there is a simpler way: as we use `ament_generate_version_header` you simply can use
```c++
#include<hardware_interface/version.h>
#if HARDWARE_INTERFACE_VERSION_GTE(major, minor, patch) 
#endif
```

**Comment by christophfroehlich** [comment]
@JafarAbdi shall I change it? And the CI job has now a wrong `(humble)` in the title.

**Comment by JafarAbdi** [comment]
> Well, that is also a possibility. but there is a simpler way: as we use `ament_generate_version_header` you simply can use
> 
> ```c++
> #include<hardware_interface/version.h>
> #if HARDWARE_INTERFACE_VERSION_GTE(major, minor, patch) 
> #endif
> ```

I thought about using it, but it was introduced in `4.8.0` :crying_cat_face:

**Comment by JafarAbdi** [comment]
> @JafarAbdi shall I change it? And the CI job has now a wrong `(humble)` in the title.

It should be fixed now

**Comment by christophfroehlich** [comment]
> I thought about using it, but it was introduced in `4.8.0` 😿

Oh, we should backport that :see_no_evil:

**Comment by christophfroehlich** [comment]
We have it now in the [humble](https://github.com/ros-controls/ros2_control/tree/humble) branch as well, maybe you'd consider updating this after the next release of ros2_control.

**Comment by JafarAbdi** [comment]
> We have it now in the [humble](https://github.com/ros-controls/ros2_control/tree/humble) branch as well, maybe you'd consider updating this after the next release of ros2_control.

Thanks! I'll open a PR to use it

**Pull request merged**
